use CompraVenta

-- Esto Elimina todo los que sean 0
delete from TM_USUARIO where est=0

select * from TM_EMPRESA
select * from TM_SUCURSAL
select * from TM_COMPANIA
select * from TM_USUARIO
select * from TM_CATEGORIA
select * from TM_MONEDA
select * from  TM_UNIDAD
select * from TM_CLIENTE
select * from TM_MENU
select * from TM_ROL
select * from TM_PROVEEDOR



sp_helptext SP_L_MENU_01


SELECT * FROM TM_SUCURSAL
SELECT * FROM TM_CLIENTE

sp_helptext SP_L_CLIENTE_01
select * From TM_CLIENTE


select * from TM_PROVEEDOR

sp_helptext SP_U_PRODUCTO_01

select * from TM_PRODUCTO

sp_helptext SP_L_PROVEEDOR_02

select * from TM_USUARIO
select * from TM_ROL
select * from TM_MENU
select * from TD_MENU

ALTER PROCEDURE SP_L_MENU_01
@ROL_ID INT
AS
BEGIN
SELECT
	TD_MENU.MEND_ID, 
	TD_MENU.MEN_ID, 
	TD_MENU.ROL_ID, 
	TD_MENU.MEND_PERMI, 
	TD_MENU.FECH_CREA, 
	TD_MENU.EST, 
	TM_MENU.MEN_NOM, 
	TM_MENU.MEN_RUTA, 
	TM_MENU.MEN_IDENTI,
	TM_MENU.MEN_GRUPO
	FROM        
	TD_MENU INNER JOIN
	TM_MENU ON TD_MENU.MEN_ID = TM_MENU.MEN_ID
	WHERE
	TD_MENU.ROL_ID = @ROL_ID

END

ALTER PROCEDURE SP_U_MENU_01
@MEND_ID INT 
AS 
BEGIN 
    UPDATE TD_MENU
    SET
        MEND_PERMI = 'SI'
    WHERE 
        MEND_ID = @MEND_ID
END

ALTER PROCEDURE SP_U_MENU_02
@MEND_ID INT 
AS 
BEGIN 
    UPDATE TD_MENU
    SET
        MEND_PERMI = 'NO'
    WHERE 
        MEND_ID = @MEND_ID
END


CREATE PROCEDURE SP_U_USUARIO_03
@USU_ID INT,
@USU_PASS VARCHAR(50)
AS
BEGIN
	UPDATE TM_USUARIO
	SET
		USU_PASS = @USU_PASS
	WHERE 
		USU_ID = @USU_ID
END

select * from TM_USUARIO


select * from TM_MENU
select * from TD_MENU


update TM_MENU
set 
	FECH_CREA = getdate()
where 
	FECH_CREA is null 

update TD_MENU
set 
	FECH_CREA = getdate()
where 
	FECH_CREA is null

Delete from TM_EMPRESA
where EMP_ID = 12

select * from TM_EMPRESA

SELECT * FROM tm_proveedor WHERE emp_id = 1 AND est = 1;

EXEC sp_helptext 'SP_L_PROVEEDOR_01';

SELECT name FROM sys.procedures WHERE name = 'SP_L_PROVEEDOR_01';


-- Listar todas los Proveedores 
ALTER PROCEDURE SP_L_PROVEEDOR_01  
@EMP_ID INT  
AS  
BEGIN  
 SELECT * FROM TM_PROVEEDOR  
 WHERE  
 EMP_ID = @EMP_ID  
 AND EST = 1  
END

EXEC SP_L_PROVEEDOR_02 @PROV_ID = 64;

select * from TM_USUARIO
select * from TM_EMPRESA
select * from TM_PROVEEDOR


SELECT * FROM TM_PROVEEDOR WHERE EMP_ID = 1 AND EST = 1


DELETE FROM TM_PROVEEDOR
WHERE est = 0;

SELECT * FROM TM_PROVEEDOR WHERE PROV_ID = 1

sp_helptext SP_L_PRODUCTO_02 

-- Obtener registro por ID  
ALTER PROCEDURE SP_L_PROVEEDOR_02  
@PROV_ID INT  
AS  
BEGIN   
 SELECT * FROM TM_PROVEEDOR  
 WHERE  
 PROV_ID = @PROV_ID  
END

EXEC SP_L_PRODUCTO_03

CREATE PROCEDURE SP_L_PRODUCTO_03    
@CAT_ID INT    
AS    
BEGIN    
SELECT          
TM_PRODUCTO.PROD_ID,   
TM_PRODUCTO.SUC_ID,   
TM_PRODUCTO.CAT_ID,   
TM_PRODUCTO.PROD_NOM,   
TM_PRODUCTO.PROD_DESCRIP,   
TM_PRODUCTO.UND_ID,   
TM_PRODUCTO.MON_ID,   
TM_PRODUCTO.PROD_PCOMPRA,   
TM_PRODUCTO.PROD_PVENTA,   
TM_PRODUCTO.PROD_STOCK,   
TM_PRODUCTO.PROD_FECHAVEN,   
TM_PRODUCTO.PROD_IMG,   
TM_PRODUCTO.FECH_CREA,   
TM_PRODUCTO.EST,   
TM_CATEGORIA.CAT_NOM,   
TM_MONEDA.MON_NOM,   
TM_UNIDAD.UND_NOM  
FROM              
TM_PRODUCTO INNER JOIN  
TM_CATEGORIA ON TM_PRODUCTO.CAT_ID = TM_CATEGORIA.CAT_ID INNER JOIN  
TM_MONEDA ON TM_PRODUCTO.MON_ID = TM_MONEDA.MON_ID INNER JOIN  
TM_UNIDAD ON TM_PRODUCTO.UND_ID = TM_UNIDAD.UND_ID  
 WHERE    
 TM_PRODUCTO. CAT_ID = @CAT_ID    
 AND TM_PRODUCTO.EST=1    
END 

select * From TM_PRODUCTO
select * from TM_UNIDAD

--Obtener registro por ID  
ALTER PROCEDURE SP_L_PRODUCTO_02  
@PROD_ID INT  
AS  
BEGIN  
 SELECT          
TM_PRODUCTO.PROD_ID,   
TM_PRODUCTO.SUC_ID,   
TM_PRODUCTO.CAT_ID,   
TM_PRODUCTO.PROD_NOM,   
TM_PRODUCTO.PROD_DESCRIP,   
TM_PRODUCTO.UND_ID,   
TM_PRODUCTO.MON_ID,   
TM_PRODUCTO.PROD_PCOMPRA,   
TM_PRODUCTO.PROD_PVENTA,   
TM_PRODUCTO.PROD_STOCK,   
TM_PRODUCTO.PROD_FECHAVEN,   
TM_PRODUCTO.PROD_IMG,   
TM_PRODUCTO.FECH_CREA,   
TM_PRODUCTO.EST,   
TM_CATEGORIA.CAT_NOM,   
TM_MONEDA.MON_NOM,   
TM_UNIDAD.UND_NOM  
FROM              
TM_PRODUCTO INNER JOIN  
TM_CATEGORIA ON TM_PRODUCTO.CAT_ID = TM_CATEGORIA.CAT_ID INNER JOIN  
TM_MONEDA ON TM_PRODUCTO.MON_ID = TM_MONEDA.MON_ID INNER JOIN  
TM_UNIDAD ON TM_PRODUCTO.UND_ID = TM_UNIDAD.UND_ID  
 WHERE  
 TM_PRODUCTO.PROD_ID = @PROD_ID  
END

CREATE PROCEDURE SP_L_PAGO_01

AS
BEGIN
	SELECT * FROM TM_PAGO WHERE EST=1
END

select * from TM_PAGO
select * from TM_

select * from TD_COMPRA_DETALLE
select * from TM_COMPRA
select * from TD_COMPRA_DETALLE


DBCC CHECKIDENT('TM_PAGO', RESEED, 0);

select * from TM_COMPRA