use CompraVenta

-- Esto Elimina todo los que sean 0
delete from TM_USUARIO where est=0

select * from TM_EMPRESA
select * from TM_SUCURSAL
select * from TM_COMPANIA
select * from TM_USUARIO
select * from TM_CATEGORIA
select * from TM_MONEDA
select * from  TM_UNIDAD
select * from TM_CLIENTE
select * from TM_MENU
select * from TM_ROL


sp_helptext SP_L_MENU_01


SELECT * FROM TM_SUCURSAL
SELECT * FROM TM_CLIENTE

sp_helptext SP_L_CLIENTE_01
select * From TM_CLIENTE


select * from TM_PROVEEDOR

sp_helptext SP_U_PRODUCTO_01

select * from TM_PRODUCTO

sp_helptext SP_U_MENU_01

select * from TM_USUARIO
select * from TM_ROL
select * from TM_SUCURSAL

ALTER PROCEDURE SP_L_MENU_01
@ROL_ID INT
AS
BEGIN
SELECT
	TD_MENU.MEND_ID, 
	TD_MENU.MEN_ID, 
	TD_MENU.ROL_ID, 
	TD_MENU.MEND_PERMI, 
	TD_MENU.FECH_CREA, 
	TD_MENU.EST, 
	TM_MENU.MEN_NOM, 
	TM_MENU.MEN_RUTA, 
	TM_MENU.MEN_IDENTI,
	TM_MENU.MEN_GRUPO
	FROM        
	TD_MENU INNER JOIN
	TM_MENU ON TD_MENU.MEN_ID = TM_MENU.MEN_ID
	WHERE
	TD_MENU.ROL_ID = @ROL_ID

END

ALTER PROCEDURE SP_U_MENU_01
@MEND_ID INT 
AS 
BEGIN 
    UPDATE TD_MENU
    SET
        MEND_PERMI = 'SI'
    WHERE 
        MEN_ID = @MEND_ID
END

ALTER PROCEDURE SP_U_MENU_02
@MEND_ID INT 
AS 
BEGIN 
    UPDATE TD_MENU
    SET
        MEND_PERMI = 'NO'
    WHERE 
        MEN_ID = @MEND_ID
END

UPDATE TD_MENU SET MEND_PERMI = 'SI' WHERE MEND_PERMI = 'Si';
UPDATE TD_MENU SET MEND_PERMI = 'NO' WHERE MEND_PERMI = 'No';

select * from TM_ROL

-- Cambia el valor de @ROL_ID por el ID del rol que quieres habilitar
DECLARE @ROL_ID INT = 1;

UPDATE TD_MENU
SET MEND_PERMI = 'SI', EST = 1
WHERE ROL_ID = @ROL_ID;

DECLARE @ROL_ID INT = 1;  -- Cambia 1 por el ID de tu rol

UPDATE TD_MENU
SET MEND_PERMI = 'SI', EST = 1
WHERE ROL_ID = @ROL_ID;

SELECT * FROM TD_MENU WHERE ROL_ID = 1 AND EST = 1; 
UPDATE TD_MENU SET MEND_PERMI = 'Si' WHERE MEND_PERMI = 'SI';