-- Create Procedure --
CREATE PROCEDURE SP_L_COMPANIA_01
AS
BEGIN 
	SELECT * FROM TM_COMPANIA
END


-- Listar todas las registros por Sucursal
ALTER PROCEDURE SP_L_COMPANIA_01
AS
BEGIN
	SELECT * FROM TM_COMPANIA
	WHERE
	EST = 1
END

-- Obtener registro por ID
CREATE PROCEDURE SP_L_COMPANIA_02
@COM_ID INT
AS
BEGIN 
	SELECT * FROM TM_COMPANIA
	WHERE
	COM_ID = @COM_ID
END

-- ELiminar Registro
CREATE PROCEDURE SP_D_COMPANIA_01
@COM_ID INT
AS
BEGIN
	UPDATE TM_COMPANIA
	SET
		EST = 0
	WHERE 
		COM_ID = @COM_ID
END

-- Registrar nuevo Registro
CREATE PROCEDURE SP_I_COMPANIA_01
@COM_NOM VARCHAR(150)
AS
BEGIN
	INSERT INTO TM_COMPANIA
	(COM_NOM,FECH_CREA,EST)
	VALUES
	(@COM_NOM,GETDATE(),1)
END

-- Actualizar Registro
CREATE PROCEDURE SP_U_COMPANIA_01
@COM_ID INT,
@COM_NOM VARCHAR(150)
AS
BEGIN
	UPDATE TM_COMPANIA
	SET
		COM_NOM = @COM_NOM
	WHERE
		COM_ID = @COM_ID
END