use CompraVenta
go

-- Create Procedure --
CREATE PROCEDURE SP_L_EMPRESA_01
AS
BEGIN 
	SELECT * FROM TM_EMPRESA
END


-- Listar todas las registros por Sucursal
ALTER PROCEDURE SP_L_EMPRESA_01
@COM_ID INT 
AS
BEGIN
	SELECT * FROM TM_EMPRESA
	WHERE
	COM_ID = @COM_ID
	AND EST = 1
END

-- Obtener registro por ID
CREATE PROCEDURE SP_L_EMPRESA_02
@EMP_ID INT
AS
BEGIN 
	SELECT * FROM TM_EMPRESA
	WHERE
	EMP_ID = @EMP_ID
END

-- ELiminar Registro
CREATE PROCEDURE SP_D_EMPRESA_01
@EMP_ID INT
AS
BEGIN
	UPDATE TM_EMPRESA
	SET
		EST = 0
	WHERE 
		EMP_ID = @EMP_ID
END

-- Registrar nuevo Registro
CREATE PROCEDURE SP_I_EMPRESA_01
@COM_ID INT,
@EMP_NOM VARCHAR(150),
@EMP_RUC VARCHAR(150)
AS
BEGIN
	INSERT INTO TM_EMPRESA
	(EMP_NOM,EMP_RUC,FECH_CREA,EST)
	VALUES
	(@EMP_NOM,@EMP_RUC,GETDATE(),1)
END

-- Actualizar Registro
CREATE PROCEDURE SP_U_EMPRESA_01
@EMP_ID INT,
@COM_ID INT,
@EMP_NOM VARCHAR(150),
@EMP_RUC VARCHAR(150)
AS
BEGIN
	UPDATE TM_EMPRESA
	SET
		COM_ID = @COM_ID,
		EMP_NOM = @EMP_NOM,
		EMP_RUC = @EMP_RUC
	WHERE
		EMP_ID = @EMP_ID
END